blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/JsonViewer-Component/Blazor/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://jsonviewer-component.github.io/Blazor/
    about: Read the documentation for help and guidance
  - name: ðŸ’¡ Stack Overflow
    url: https://stackoverflow.com/questions/tagged/jsonviewer-blazor
    about: Ask questions on Stack Overflow with the tag 'jsonviewer-blazor'

